services:
  - name: docker:dind
    command: [ "--tls=false" ]

variables:
  #  TESTCONTAINERS_HOST_OVERRIDE: "host.docker.internal"
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true

  MAVEN_CLI_OPTS: >-
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    --no-transfer-progress
#    -DinstallAtEnd=true

  INT_TEST_DISABLE: >-
    -Dskip.integration.tests=true

  INT_TEST_ENABLE: >-
    -Dskip.integration.tests=false

image: maven:3-openjdk-8
cache:
  paths:
    - .m2/repository

stages:
  - build
  - test
  - deploy

deploy:
  stage: deploy
  script:
    - echo "Deploy to staging server"
  environment:
    name: staging
    url: https://staging.example.com


build:
  stage: build
  script:
    - 'mvn $MAVEN_CLI_OPTS install $INT_TEST_DISABLE'
  except:
    variables:
      - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

test:
  stage: test
  script:
    - 'mvn $MAVEN_CLI_OPTS org.jacoco:jacoco-maven-plugin:0.8.8:prepare-agent verify org.jacoco:jacoco-maven-plugin:0.8.8:report $INT_TEST_ENABLE'
  needs: ["build"]
  artifacts:
    when: always
    paths:
        - liquibase-couchbase/target/site/jacoco/jacoco.xml
    reports:
      junit:
        - liquibase-couchbase/target/surefire-reports/TEST-*.xml
        - liquibase-couchbase/target/failsafe-reports/TEST-*.xml
  except:
    variables:
      - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH