# This workflow will build the extension against the latest Liquibase artifact
name: "Nightly build"

on:
    workflow_dispatch:
    schedule:
        - cron: '0 7 * * 1-5'

jobs:
    nightly-build:
        uses: liquibase/build-logic/.github/workflows/os-extension-test.yml@94733f237ff590ba7b27a881dcfdd1146a0bc943 # v0.6.4
        with:
            nightly: true
        secrets: inherit