name: Create Release

on:
    push:
        branches:
            - main

jobs:
    create-release:
        name: Create Release
        runs-on: ubuntu-latest
        steps:
            -   name: Create Release Draft
                id: create-release
                uses: release-drafter/release-drafter@v5
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}